name: TestRelease

on:
  push:
    branches:
      - cs-test-workflow
    paths-ignore:
      - 'docs/**'
      - 'docs-web/**'
      - 'examples/**'
      - 'examples-of-custom-resources/**'
      - '**.md'
  create:
    tags:
      - 'v[0-9].[0-9].[0-9]+*'

defaults:
  run:
    shell: bash

env:
  DOCKER_BUILDKIT: 1
  DOCKER_IMAGE: nginx/nginx-ingress
  GOLANG_VERSION: 1.15
  K8S_TIMEOUT: 75s
  HELM_CHART_DIR: deployments/helm-chart
  GIT_NAME: NGINX Kubernetes Team
  GIT_MAIL: kubernetes@nginx.com

jobs:

  release-plus-docker:
    name: Release Plus Images
    runs-on: ubuntu-18.04
    steps:
      - name: GCR Login
        uses: docker/login-action@v1 
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Pull from GCR and save
        env:
          UPLOADER_CERT: ${{ secrets.KIC_UPLOADER_CRT }}
          UPLOADER_KEY: ${{ secrets.KIC_UPLOADER_KEY }}
        run: |
          docker pull gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic/nginx-ingress-plus:29a599a
          docker pull gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic/nginx-ingress-plus:29a599a-opentracing
          docker pull gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic/nginx-ingress-plus:29a599a-ubi
          docker pull gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic-nap/nginx-ingress-plus-ap:29a599a
          docker pull gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic-nap/nginx-ingress-plus-ap:29a599a-ubi
          echo "$UPLOADER_CERT" > kic-uploader.crt
          echo "$UPLOADER_KEY" > kic-uploader.key
          docker tag gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic/nginx-ingress-plus:29a599a nginx-ic/nginx-plus-ingress:29a599a
          docker tag gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic/nginx-ingress-plus:29a599a-opentracing nginx-ic/nginx-plus-ingress:29a599a-opentracing
          docker tag gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic/nginx-ingress-plus:29a599a-ubi nginx-ic/nginx-plus-ingress:29a599a-ubi
          docker tag gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic-nap/nginx-ingress-plus-ap:29a599a nginx-ic-nap/nginx-plus-ingress-ap:29a599a
          docker tag gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nginx-ic-nap/nginx-ingress-plus-ap:29a599a-ubi nginx-ic-nap/nginx-plus-ingress-ap:29a599a-ubi
          docker save nginx-ic/nginx-plus-ingress:29a599a \
                      nginx-ic/nginx-plus-ingress:29a599a-opentracing \
                      nginx-ic/nginx-plus-ingress:29a599a-ubi \
                      nginx-ic-nap/nginx-plus-ingress-ap:29a599a \
                      nginx-ic-nap/nginx-plus-ingress-ap:29a599a-ubi | gzip > nginx-ic-test.tar.gz
          curl -F "file=@nginx-ic-test.tar.gz" --cert kic-uploader.crt --key kic-uploader.key  https://up-ap.nginx.com/
